CREATE TABLE admins (
	id BIGINT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(191) NOT NULL,
	email VARCHAR(191) NOT NULL UNIQUE,
	password_hash VARCHAR(191) NOT NULL,
	role VARCHAR(50) NOT NULL DEFAULT 'admin',
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	deleted_at TIMESTAMP NULL DEFAULT NULL
);


CREATE TABLE teams (
	  id BIGINT AUTO_INCREMENT PRIMARY KEY,
	  name VARCHAR(191) NOT NULL,
	  logo_path VARCHAR(512) NULL,
	  founded_year INT NULL,
	  address VARCHAR(512) NULL,
	  city VARCHAR(191) NULL,
	  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	  deleted_at TIMESTAMP NULL DEFAULT NULL,
	  UNIQUE (name)
);


CREATE TABLE players (
	id BIGINT AUTO_INCREMENT PRIMARY KEY,
	team_id BIGINT NOT NULL,
	name VARCHAR(191) NOT NULL,
	height_cm INT NULL,
	weight_kg INT NULL,
	position ENUM('penyerang','gelandang','bertahan','penjaga_gawang') NOT NULL,
	jersey_number INT NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	deleted_at TIMESTAMP NULL DEFAULT NULL
);


CREATE TABLE matches (
	id BIGINT AUTO_INCREMENT PRIMARY KEY,
	scheduled_at DATETIME NOT NULL,
	home_team_id BIGINT NOT NULL,
	away_team_id BIGINT NOT NULL,
	home_score INT DEFAULT 0,
	away_score INT DEFAULT 0,
	status ENUM('scheduled','finished','cancelled') DEFAULT 'scheduled',
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	deleted_at TIMESTAMP NULL DEFAULT NULL
);

CREATE TABLE goals (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  match_id BIGINT NOT NULL,
  player_id BIGINT NOT NULL,
  team_id BIGINT NOT NULL,
  minute_scored INT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE token_blacklist (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  jti VARCHAR(191) NOT NULL UNIQUE,
  expires_at DATETIME NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);